export const actionTypes = {
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
  SET_FEATURE_PRODUCT_LIST: 'SET_FEATURE_PRODUCT_LIST',
  SET_CATEGORY_LIST: 'SET_CATEGORY_LIST',

  SET_USER_INFO: 'SET_USER_INFO',
  SET_USER_FAVOURITE_PRODUCTS: 'SET_USER_FAVOURITE_PRODUCTS',

  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  MAKE_CART_EMPTY: 'MAKE_CART_EMPTY',
  INCREMENT_QUANTITY_IN_CART: 'INCREMENT_QUANTITY_IN_CART',
  DECREMENT_QUANTITY_IN_CART: 'DECREMENT_QUANTITY_IN_CART',
};
